### ISSUE TITLE
Lab report 1 feedback

### ISSUE THREAD

**Issue by daniel-n-ryu** [atorshizi/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [ ] All relevant URLs written as markdown links
  - URL link for VScode does not work
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Needs keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Well done! It looks good, just need to fix the link and add keystrokes to the last section
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

---------

**Comment by atorshizi** [comment]
I was just a little confused as to what the "counting keystrokes" criteria meant in the rubric and wanted to clarify. I added a section to part 6 where i talk about how entering all commands at once reduces the number of times i press enter and other keys and so compared with entering the commands separately i would save 5 keystrokes. I just wanted to make sure that what I have is what the rubric is looking for.
Thanks,
Arian

**Comment by daniel-n-ryu** [comment]
Sorry for not responding, everything was done correctly. Well done
